### PR TITLE
Update Firebase Peer Dependency

### PR DESCRIPTION
**Pull request by MaCleodWalker**
Changes:
Updated Firebase peer dependency to version 10.0.0 from 9.0.0 to align with the latest stable release.
Verified compatibility with the existing codebase and other dependencies.

### CODE REVIEW

**Comment by Dev1994** [comment]
Would be awesome if we could get this PR through. My github workflow currenlly fails due to this when running npm run preview.

**Comment by brandonbaraban** [comment]
@Dev1994 Until this is merged, I've been avoiding errors by adding the `--legacy-peer-deps` option to `npm install` commands. If the Firebase GitHub Action is running some `npm install` command that is failing, you can [configure your project with a `.npmrc` with that option enabled](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps).

Note that this is generally not recommended, as you will have to manually make sure your project is installing compatible peer dependencies. My project is simple enough that it's not an issue for now. Hope this helps!

**Comment by TobyNorhave** [comment]
Agreed on this part! - Please update the dependencies for firebase. I love your SvelteFire 🔥

**Comment by eyeofastarte** [comment]
`+1` Through when using legacy dependencies, my Cloudflare build was failing. @brandonbaraban mentioned the fix, I also found it here: https://stackoverflow.com/a/73433707

```npmrc
# .npmrc
legacy-peer-deps=true
```

**Pull request closed without merging**
